### ISSUE TITLE
Great impression

### ISSUE THREAD

**Issue by tommygebru** [DeemCreative/prj-rev-bwfs-dasmoto#1]
_Moving forward into Teacozy_ Im gonna ask that you adhere to the pdf guidelines, which will help the next Project Reviewer assess and deliver feedback ✅ 

Great impression on your first submittable project Irene, I can see that your codebase is sprawling with activity, its exciting to see you work on this from multiple fronts. While the Dasmoto Project has a pdf file that serves as a guideline and expected outcome. Your time, effort and knowledge of the web development fundamentals really shows in your Dasmoto store front. 😁

**Comment by DeemCreative** [comment]
Thanks so much for helping me. Really appreciate it. Sorry about the PDF guidelines, somehow I missed that.
